export const sliderData = [
  {
    title: 'Bike',
    image: require('../assets/images/homescreen/bike.png'),
  },
  {
    title: 'Car',
    image: require('../assets/images/homescreen/car.png'),
  },
  {
    title: 'Rickshaw',
    image: require('../assets/images/homescreen/rickshaw.png'),
  },
  {
    title: 'Bus',
    image: require('../assets/images/homescreen/bus.png'),
  },
  {
    title: 'Other',
    image: require('../assets/images/homescreen/bus.png'),
  },
];

export const paidGames = [
  {
    poster: require('../assets/images/spiderman.webp'),
    title: 'Lahore',
    subtitle: 'Ali',
    isFree: 'No',
    price: 'RS.40',
    id: '1',
  },
  {
    poster: require('../assets/images/battlefield-2042.webp'),
    title: 'Faisalabad',
    subtitle: 'Zain',
    isFree: 'No',
    price: 'RS.20',
    id: '2',
  },
  {
    poster: require('../assets/images/miles-morales.webp'),
    title: 'Hyderabad',
    subtitle: 'M Waqar',
    isFree: 'No',
    price: 'RS.30',
    id: '3',
  },
  {
    poster: require('../assets/images/spiderman.webp'),
    title: 'Lahore',
    subtitle: 'Ali',
    isFree: 'No',
    price: 'RS.40',
    id: '4',
  },
  {
    poster: require('../assets/images/battlefield-2042.webp'),
    title: 'Faisalabad',
    subtitle: 'Zain',
    isFree: 'No',
    price: 'RS.20',
    id: '5',
  },
  {
    poster: require('../assets/images/miles-morales.webp'),
    title: 'Hyderabad',
    subtitle: 'M Waqar',
    isFree: 'No',
    price: 'RS.30',
    id: '6',
  },
  {
    poster: require('../assets/images/spiderman.webp'),
    title: 'Lahore',
    subtitle: 'Ali',
    isFree: 'No',
    price: 'RS.40',
    id: '7',
  },
  {
    poster: require('../assets/images/battlefield-2042.webp'),
    title: 'Faisalabad',
    subtitle: 'Zain',
    isFree: 'No',
    price: 'RS.20',
    id: '8',
  },
  {
    poster: require('../assets/images/miles-morales.webp'),
    title: 'Hyderabad',
    subtitle: 'M Waqar',
    isFree: 'No',
    price: 'RS.30',
    id: '9',
  },
  {
    poster: require('../assets/images/spiderman.webp'),
    title: 'Lahore',
    subtitle: 'Ali',
    isFree: 'No',
    price: 'RS.40',
    id: '10',
  },
  {
    poster: require('../assets/images/battlefield-2042.webp'),
    title: 'Faisalabad',
    subtitle: 'Zain',
    isFree: 'No',
    price: 'RS.20',
    id: '11',
  },
  {
    poster: require('../assets/images/miles-morales.webp'),
    title: 'Hyderabad',
    subtitle: 'M Waqar',
    isFree: 'No',
    price: 'RS.30',
    id: '12',
  },
  {
    poster: require('../assets/images/spiderman.webp'),
    title: 'Lahore',
    subtitle: 'Ali',
    isFree: 'No',
    price: 'RS.40',
    id: '13',
  },
  {
    poster: require('../assets/images/battlefield-2042.webp'),
    title: 'Faisalabad',
    subtitle: 'Zain',
    isFree: 'No',
    price: 'RS.20',
    id: '14',
  },
  {
    poster: require('../assets/images/miles-morales.webp'),
    title: 'Hyderabad',
    subtitle: 'M Waqar',
    isFree: 'No',
    price: 'RS.30',
    id: '15',
  },
  {
    poster: require('../assets/images/spiderman.webp'),
    title: 'Lahore',
    subtitle: 'Ali',
    isFree: 'No',
    price: 'RS.40',
    id: '16',
  },
  {
    poster: require('../assets/images/battlefield-2042.webp'),
    title: 'Faisalabad',
    subtitle: 'Zain',
    isFree: 'No',
    price: 'RS.20',
    id: '17',
  },
  {
    poster: require('../assets/images/miles-morales.webp'),
    title: 'Hyderabad',
    subtitle: 'M Waqar',
    isFree: 'No',
    price: 'RS.30',
    id: '18',
  },
  {
    poster: require('../assets/images/spiderman.webp'),
    title: 'Lahore',
    subtitle: 'Ali',
    isFree: 'No',
    price: 'RS.40',
    id: '19',
  },
  {
    poster: require('../assets/images/battlefield-2042.webp'),
    title: 'Faisalabad',
    subtitle: 'Zain',
    isFree: 'No',
    price: 'RS.20',
    id: '20',
  },
  {
    poster: require('../assets/images/miles-morales.webp'),
    title: 'Hyderabad',
    subtitle: 'M Waqar',
    isFree: 'No',
    price: 'RS.30',
    id: '22',
  },
  
];

export const freeGames = [
  {
    poster: require('../assets/images/Altos-Odyssey.jpeg'),
    title: 'Faisalabad',
    subtitle: 'Ali Hassan',
    isFree: 'Yes',
    id: '1',
  },
  {
    poster: require('../assets/images/asphalt-9.jpeg'),
    title: 'Lahore',
    subtitle: 'Kashif',
    isFree: 'Yes',
    id: '2',
  },
  {
    poster: require('../assets/images/genshin-impact.jpeg'),
    title: 'Karachi',
    subtitle: 'Raza',
    isFree: 'Yes',
    id: '3',
  },
  {
    poster: require('../assets/images/fortnite.webp'),
    title: 'Multan',
    subtitle: 'Hamza',
    isFree: 'Yes',
    id: '4',
  },
  {
    poster: require('../assets/images/pokemon-unite.jpeg'),
    title: 'Faisalabad',
    subtitle: 'Faizan',
    isFree: 'Yes',
    id: '5',
  },
  {
    poster: require('../assets/images/diablo-4.jpeg'),
    title: 'Lahore',
    subtitle: 'Majid',
    isFree: 'No',
    id: '6',
  },
  {
    poster: require('../assets/images/Altos-Odyssey.jpeg'),
    title: 'Faisalabad',
    subtitle: 'Ali Hassan',
    isFree: 'Yes',
    id: '7',
  },
  {
    poster: require('../assets/images/asphalt-9.jpeg'),
    title: 'Lahore',
    subtitle: 'Kashif',
    isFree: 'Yes',
    id: '8',
  },
  {
    poster: require('../assets/images/genshin-impact.jpeg'),
    title: 'Karachi',
    subtitle: 'Raza',
    isFree: 'Yes',
    id: '9',
  },
  {
    poster: require('../assets/images/fortnite.webp'),
    title: 'Multan',
    subtitle: 'Hamza',
    isFree: 'Yes',
    id: '10',
  },
  {
    poster: require('../assets/images/pokemon-unite.jpeg'),
    title: 'Faisalabad',
    subtitle: 'Faizan',
    isFree: 'Yes',
    id: '11',
  },
  {
    poster: require('../assets/images/diablo-4.jpeg'),
    title: 'Lahore',
    subtitle: 'Majid',
    isFree: 'No',
    id: '12',
  },
  {
    poster: require('../assets/images/Altos-Odyssey.jpeg'),
    title: 'Faisalabad',
    subtitle: 'Ali Hassan',
    isFree: 'Yes',
    id: '13',
  },
  {
    poster: require('../assets/images/asphalt-9.jpeg'),
    title: 'Lahore',
    subtitle: 'Kashif',
    isFree: 'Yes',
    id: '14',
  },
  {
    poster: require('../assets/images/genshin-impact.jpeg'),
    title: 'Karachi',
    subtitle: 'Raza',
    isFree: 'Yes',
    id: '15',
  },
  {
    poster: require('../assets/images/fortnite.webp'),
    title: 'Multan',
    subtitle: 'Hamza',
    isFree: 'Yes',
    id: '16',
  },
  {
    poster: require('../assets/images/pokemon-unite.jpeg'),
    title: 'Faisalabad',
    subtitle: 'Faizan',
    isFree: 'Yes',
    id: '17',
  },
  {
    poster: require('../assets/images/diablo-4.jpeg'),
    title: 'Lahore',
    subtitle: 'Majid',
    isFree: 'No',
    id: '18',
  },
  {
    poster: require('../assets/images/Altos-Odyssey.jpeg'),
    title: 'Faisalabad',
    subtitle: 'Ali Hassan',
    isFree: 'Yes',
    id: '19',
  },
  {
    poster: require('../assets/images/asphalt-9.jpeg'),
    title: 'Lahore',
    subtitle: 'Kashif',
    isFree: 'Yes',
    id: '20',
  },
  {
    poster: require('../assets/images/genshin-impact.jpeg'),
    title: 'Karachi',
    subtitle: 'Raza',
    isFree: 'Yes',
    id: '21',
  },
  {
    poster: require('../assets/images/fortnite.webp'),
    title: 'Multan',
    subtitle: 'Hamza',
    isFree: 'Yes',
    id: '22',
  },
  {
    poster: require('../assets/images/pokemon-unite.jpeg'),
    title: 'Faisalabad',
    subtitle: 'Faizan',
    isFree: 'Yes',
    id: '23',
  },
  {
    poster: require('../assets/images/diablo-4.jpeg'),
    title: 'Lahore',
    subtitle: 'Majid',
    isFree: 'No',
    id: '24',
  },
];